//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Data.Objects;

namespace DbRelationshipInDbContextLib.EF
{
    public partial class ClassRegDemoEntities : DbContext
    {
        public ClassRegDemoEntities()
            : this(false) { }
    
        public ClassRegDemoEntities(bool proxyCreationEnabled)	    
            : base("name=ClassRegDemoEntities")
        {
            this.Configuration.ProxyCreationEnabled = proxyCreationEnabled;
        }
    
        public ClassRegDemoEntities(string connectionString)
          : this(connectionString, false) { }
    
        public ClassRegDemoEntities(string connectionString, bool proxyCreationEnabled)
            : base(connectionString)
        {
            this.Configuration.ProxyCreationEnabled = proxyCreationEnabled;
        }	
    
        public ObjectContext ObjectContext
        {
          get { return ((IObjectContextAdapter)this).ObjectContext; }
        }
    
    	protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    	
        public DbSet<Class> Classes { get; set; }
        public DbSet<Club> Clubs { get; set; }
        public DbSet<Student> Students { get; set; }
        public DbSet<StudentClubMatch> StudentClubMatches { get; set; }
        public DbSet<Teacher> Teachers { get; set; }
    }
}
