//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace DbRelationshipInDbContextLib.EF
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Club))]
    [KnownType(typeof(Student))]
    public partial class StudentClubMatch
    {
        [DataMember]
        public int StudentId { get; set; }
        [DataMember]
        public int ClubId { get; set; }
        [DataMember]
        public bool IsCommiteMember { get; set; }
    
        [DataMember]
        public virtual Club Club { get; set; }
        [DataMember]
        public virtual Student Student { get; set; }
    }
    
}
