//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace DbRelationshipInDbContextLib.EF
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Class))]
    public partial class Teacher
    {
        public Teacher()
        {
            this.Classes = new HashSet<Class>();
        }
    
        [DataMember]
        public int Id { get; set; }
        [DataMember]
        public string Name { get; set; }
        [DataMember]
        public string Address { get; set; }
        [DataMember]
        public string City { get; set; }
        [DataMember]
        public string State { get; set; }
        [DataMember]
        public string Country { get; set; }
        [DataMember]
        public Nullable<int> Zip { get; set; }
    
        [DataMember]
        public virtual ICollection<Class> Classes { get; set; }
    }
    
}
